<?php
/**
 * PaymentmethodsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PaymentmethodsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentmethodsApi
{

    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://api.authorize.net/v1');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return PaymentmethodsApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createPaymentMethod
     *
     * Create A Payment Method.
     *
     * @param string $customer_id Customer ID (required)
     * @param \Swagger\Client\Model\CreatePaymentMethod $create_payment_method the \&quot;CreatePaymentMethod\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \Swagger\Client\Model\PaymentMethod
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createPaymentMethod($customer_id, $create_payment_method, $authorization = null)
    {
        list($response) = $this->createPaymentMethodWithHttpInfo($customer_id, $create_payment_method, $authorization);
        return $response;
    }


    /**
     * Operation createPaymentMethodWithHttpInfo
     *
     * Create A Payment Method.
     *
     * @param string $customer_id Customer ID (required)
     * @param \Swagger\Client\Model\CreatePaymentMethod $create_payment_method the \&quot;CreatePaymentMethod\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \Swagger\Client\Model\PaymentMethod, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createPaymentMethodWithHttpInfo($customer_id, $create_payment_method, $authorization = null)
    {
        
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling createPaymentMethod');
        }

        // verify the required parameter 'create_payment_method' is set
        if ($create_payment_method === null) {
            throw new \InvalidArgumentException('Missing the required parameter $create_payment_method when calling createPaymentMethod');
        }

        // parse inputs
        $resourcePath = "/customers/{customerId}/paymentmethods";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($create_payment_method)) {
            $_tempBody = $create_payment_method;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\PaymentMethod'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethod', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethod', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation deletePaymentmethod
     *
     * Delete paymentmethods.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deletePaymentmethod($customer_id, $payment_method_id, $authorization = null)
    {
        list($response) = $this->deletePaymentmethodWithHttpInfo($customer_id, $payment_method_id, $authorization);
        return $response;
    }


    /**
     * Operation deletePaymentmethodWithHttpInfo
     *
     * Delete paymentmethods.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deletePaymentmethodWithHttpInfo($customer_id, $payment_method_id, $authorization = null)
    {
        
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling deletePaymentmethod');
        }

        // verify the required parameter 'payment_method_id' is set
        if ($payment_method_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $payment_method_id when calling deletePaymentmethod');
        }

        // parse inputs
        $resourcePath = "/customers/{customerId}/paymentmethods/{paymentMethodId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }// path params
        if ($payment_method_id !== null) {
            $resourcePath = str_replace(
                "{" . "paymentMethodId" . "}",
                $this->apiClient->getSerializer()->toPathValue($payment_method_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }

            throw $e;
        }
    }
    /**
     * Operation getCustomerPaymentMethod
     *
     * Get Customer Payment Method.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \Swagger\Client\Model\PaymentMethod
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCustomerPaymentMethod($customer_id, $payment_method_id, $authorization = null)
    {
        list($response) = $this->getCustomerPaymentMethodWithHttpInfo($customer_id, $payment_method_id, $authorization);
        return $response;
    }


    /**
     * Operation getCustomerPaymentMethodWithHttpInfo
     *
     * Get Customer Payment Method.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \Swagger\Client\Model\PaymentMethod, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCustomerPaymentMethodWithHttpInfo($customer_id, $payment_method_id, $authorization = null)
    {
        
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling getCustomerPaymentMethod');
        }

        // verify the required parameter 'payment_method_id' is set
        if ($payment_method_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $payment_method_id when calling getCustomerPaymentMethod');
        }

        // parse inputs
        $resourcePath = "/customers/{customerId}/paymentmethods/{paymentMethodId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }// path params
        if ($payment_method_id !== null) {
            $resourcePath = str_replace(
                "{" . "paymentMethodId" . "}",
                $this->apiClient->getSerializer()->toPathValue($payment_method_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\PaymentMethod'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethod', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethod', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation getCustomerPaymentMethods
     *
     * Get Customer Payment Methods.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \Swagger\Client\Model\PaymentMethodCollection
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCustomerPaymentMethods($customer_id, $authorization = null)
    {
        list($response) = $this->getCustomerPaymentMethodsWithHttpInfo($customer_id, $authorization);
        return $response;
    }


    /**
     * Operation getCustomerPaymentMethodsWithHttpInfo
     *
     * Get Customer Payment Methods.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \Swagger\Client\Model\PaymentMethodCollection, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCustomerPaymentMethodsWithHttpInfo($customer_id, $authorization = null)
    {
        
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling getCustomerPaymentMethods');
        }

        // parse inputs
        $resourcePath = "/customers/{customerId}/paymentmethods";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\PaymentMethodCollection'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethodCollection', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethodCollection', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation updatePaymentMethod
     *
     * Update A paymentMethod.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param \Swagger\Client\Model\CreatePaymentMethod $create_payment_method the \&quot;UpdateAPaymentMethod\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \Swagger\Client\Model\PaymentMethod
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function updatePaymentMethod($customer_id, $payment_method_id, $create_payment_method, $authorization = null)
    {
        list($response) = $this->updatePaymentMethodWithHttpInfo($customer_id, $payment_method_id, $create_payment_method, $authorization);
        return $response;
    }


    /**
     * Operation updatePaymentMethodWithHttpInfo
     *
     * Update A paymentMethod.
     *
     * @param string $customer_id Customer ID (required)
     * @param string $payment_method_id paymentMethod ID (required)
     * @param \Swagger\Client\Model\CreatePaymentMethod $create_payment_method the \&quot;UpdateAPaymentMethod\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \Swagger\Client\Model\PaymentMethod, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function updatePaymentMethodWithHttpInfo($customer_id, $payment_method_id, $create_payment_method, $authorization = null)
    {
        
        // verify the required parameter 'customer_id' is set
        if ($customer_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $customer_id when calling updatePaymentMethod');
        }

        // verify the required parameter 'payment_method_id' is set
        if ($payment_method_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $payment_method_id when calling updatePaymentMethod');
        }

        // verify the required parameter 'create_payment_method' is set
        if ($create_payment_method === null) {
            throw new \InvalidArgumentException('Missing the required parameter $create_payment_method when calling updatePaymentMethod');
        }

        // parse inputs
        $resourcePath = "/customers/{customerId}/paymentmethods/{paymentMethodId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json'));

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                "{" . "customerId" . "}",
                $this->apiClient->getSerializer()->toPathValue($customer_id),
                $resourcePath
            );
        }// path params
        if ($payment_method_id !== null) {
            $resourcePath = str_replace(
                "{" . "paymentMethodId" . "}",
                $this->apiClient->getSerializer()->toPathValue($payment_method_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($create_payment_method)) {
            $_tempBody = $create_payment_method;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\PaymentMethod'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\PaymentMethod', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\PaymentMethod', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
