<?php
/**
 * WebhooksApi
 * PHP version 5
 *
 * @category Class
 * @package  authorizenet_rest
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Authorize.net REST API
 *
 * Authorize.net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace authorizenet_rest\Api;

use \authorizenet_rest\Configuration;
use \authorizenet_rest\ApiClient;
use \authorizenet_rest\ApiException;
use \authorizenet_rest\ObjectSerializer;

/**
 * WebhooksApi Class Doc Comment
 *
 * @category Class
 * @package  authorizenet_rest
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhooksApi
{

    /**
     * API Client
     *
     * @var \authorizenet_rest\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \authorizenet_rest\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\authorizenet_rest\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://api.authorize.net/v1');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \authorizenet_rest\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \authorizenet_rest\ApiClient $apiClient set the API client
     *
     * @return WebhooksApi
     */
    public function setApiClient(\authorizenet_rest\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation createWebhook
     *
     * Create A Webhook.
     *
     * @param \authorizenet_rest\Model\CreateWebhookBody $create_webhook_body the \&quot;CreateWebhookBody\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \authorizenet_rest\Model\GetWebhookResponse
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function createWebhook($create_webhook_body, $authorization = null)
    {
        list($response) = $this->createWebhookWithHttpInfo($create_webhook_body, $authorization);
        return $response;
    }


    /**
     * Operation createWebhookWithHttpInfo
     *
     * Create A Webhook.
     *
     * @param \authorizenet_rest\Model\CreateWebhookBody $create_webhook_body the \&quot;CreateWebhookBody\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \authorizenet_rest\Model\GetWebhookResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function createWebhookWithHttpInfo($create_webhook_body, $authorization = null)
    {
        
        // verify the required parameter 'create_webhook_body' is set
        if ($create_webhook_body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $create_webhook_body when calling createWebhook');
        }

        // parse inputs
        $resourcePath = "/webhooks";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($create_webhook_body)) {
            $_tempBody = $create_webhook_body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                '\authorizenet_rest\Model\GetWebhookResponse'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\authorizenet_rest\Model\GetWebhookResponse', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\GetWebhookResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation deleteWebhook
     *
     * Delete A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return void
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function deleteWebhook($webhook_id, $authorization = null)
    {
        list($response) = $this->deleteWebhookWithHttpInfo($webhook_id, $authorization);
        return $response;
    }


    /**
     * Operation deleteWebhookWithHttpInfo
     *
     * Delete A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function deleteWebhookWithHttpInfo($webhook_id, $authorization = null)
    {
        
        // verify the required parameter 'webhook_id' is set
        if ($webhook_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $webhook_id when calling deleteWebhook');
        }

        // parse inputs
        $resourcePath = "/webhooks/{webhookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($webhook_id !== null) {
            $resourcePath = str_replace(
                "{" . "webhookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($webhook_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'DELETE',
                $queryParams,
                $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation getWebhook
     *
     * Get A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \authorizenet_rest\Model\GetWebhookResponse
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function getWebhook($webhook_id, $authorization = null)
    {
        list($response) = $this->getWebhookWithHttpInfo($webhook_id, $authorization);
        return $response;
    }


    /**
     * Operation getWebhookWithHttpInfo
     *
     * Get A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \authorizenet_rest\Model\GetWebhookResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function getWebhookWithHttpInfo($webhook_id, $authorization = null)
    {
        
        // verify the required parameter 'webhook_id' is set
        if ($webhook_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $webhook_id when calling getWebhook');
        }

        // parse inputs
        $resourcePath = "/webhooks/{webhookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($webhook_id !== null) {
            $resourcePath = str_replace(
                "{" . "webhookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($webhook_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\authorizenet_rest\Model\GetWebhookResponse'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\authorizenet_rest\Model\GetWebhookResponse', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\GetWebhookResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation getWebhooks
     *
     * List My Webhooks.
     *
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \authorizenet_rest\Model\GetWebhookResponse[]
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function getWebhooks($authorization = null)
    {
        list($response) = $this->getWebhooksWithHttpInfo($authorization);
        return $response;
    }


    /**
     * Operation getWebhooksWithHttpInfo
     *
     * List My Webhooks.
     *
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \authorizenet_rest\Model\GetWebhookResponse[], HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function getWebhooksWithHttpInfo($authorization = null)
    {
        
        // parse inputs
        $resourcePath = "/webhooks";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\authorizenet_rest\Model\GetWebhookResponse[]'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\authorizenet_rest\Model\GetWebhookResponse[]', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\GetWebhookResponse[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation pingsWebhook
     *
     * Pings A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return void
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function pingsWebhook($webhook_id, $authorization = null)
    {
        list($response) = $this->pingsWebhookWithHttpInfo($webhook_id, $authorization);
        return $response;
    }


    /**
     * Operation pingsWebhookWithHttpInfo
     *
     * Pings A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function pingsWebhookWithHttpInfo($webhook_id, $authorization = null)
    {
        
        // verify the required parameter 'webhook_id' is set
        if ($webhook_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $webhook_id when calling pingsWebhook');
        }

        // parse inputs
        $resourcePath = "/webhooks/{webhookId}/pings";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($webhook_id !== null) {
            $resourcePath = str_replace(
                "{" . "webhookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($webhook_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
    /**
     * Operation updateWebhook
     *
     * Update A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param \authorizenet_rest\Model\CreateWebhookBody $update_webhook_body the \&quot;CreateWebhookBody\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return \authorizenet_rest\Model\GetWebhookResponse
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function updateWebhook($webhook_id, $update_webhook_body, $authorization = null)
    {
        list($response) = $this->updateWebhookWithHttpInfo($webhook_id, $update_webhook_body, $authorization);
        return $response;
    }


    /**
     * Operation updateWebhookWithHttpInfo
     *
     * Update A Webhook.
     *
     * @param string $webhook_id ID of webhook to return (required)
     * @param \authorizenet_rest\Model\CreateWebhookBody $update_webhook_body the \&quot;CreateWebhookBody\&quot; model (required)
     * @param string $authorization The value to provide in the Authorization header of ANET API request (optional)
     *
     * @return Array of \authorizenet_rest\Model\GetWebhookResponse, HTTP status code, HTTP response headers (array of strings)
     * @throws \authorizenet_rest\ApiException on non-2xx response
     */
    public function updateWebhookWithHttpInfo($webhook_id, $update_webhook_body, $authorization = null)
    {
        
        // verify the required parameter 'webhook_id' is set
        if ($webhook_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $webhook_id when calling updateWebhook');
        }

        // verify the required parameter 'update_webhook_body' is set
        if ($update_webhook_body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $update_webhook_body when calling updateWebhook');
        }

        // parse inputs
        $resourcePath = "/webhooks/{webhookId}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array());
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());

        
        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = $this->apiClient->getSerializer()->toHeaderValue($authorization);
        }
        // path params
        if ($webhook_id !== null) {
            $resourcePath = str_replace(
                "{" . "webhookId" . "}",
                $this->apiClient->getSerializer()->toPathValue($webhook_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($update_webhook_body)) {
            $_tempBody = $update_webhook_body;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'PUT',
                $queryParams,
                $httpBody,
                $headerParams,
                '\authorizenet_rest\Model\GetWebhookResponse'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, '\authorizenet_rest\Model\GetWebhookResponse', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\GetWebhookResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\authorizenet_rest\Model\ErrorResponse', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
